// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGoEnvironment() {
  return window['go']['main']['App']['CheckGoEnvironment']();
}

export function StartInstallation(arg1) {
  return window['go']['main']['App']['StartInstallation'](arg1);
}
