// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartInstall(arg1:string):Promise<any>;

export function CheckGoEnvironment():Promise<any>;

export function CloseProcess():void;
