// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckGoEnvironment():Promise<any>;

export function StartInstallation(arg1:string):Promise<any>;
