// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function StartInstall(arg1) {
  return window['go']['main']['App']['StartInstall'](arg1);
}

export function CheckGoEnvironment() {
  return window['go']['main']['App']['CheckGoEnvironment']();
}

export function CloseProcess() {
  window['go']['main']['App']['CloseProcess']();
}
